# Generated by Django 5.0.4 on 2025-04-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('branch_id', models.IntegerField()),
                ('class_id', models.CharField(max_length=2)),
                ('section', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('AY', models.DateField()),
            ],
        ),
    ]
