# Generated by Django 5.2 on 2025-04-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_branch_room_subject_teacher_alter_student_sap_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
