# Generated by Django 5.2 on 2025-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_branch_branch_id_alter_room_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsub',
            name='bs_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
