# Generated by Django 5.2 on 2025-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_branchsub_bs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaches',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
