# Generated by Django 5.2 on 2025-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sap_id',
            field=models.PositiveBigIntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
